### ISSUE TITLE
Cannot reinstall add-on

### ISSUE THREAD

**Issue by bubbl** [jelastic-jps/lets-encrypt#10] opened 2017-02-16 13:49 UTC
If you remove the add-on and then try to install it again, nothing happens, the installation notification just spins on the dashboard and no operations are performed on container.

Suspect it may be related to #8

**Comment by ihorman** [comment] 2017-03-10 18:00
Hi Bart, the bug was checked by our  QA on latest addon version and they were not able to reproduce this, we will do some additional checks and I will give you update on this. Thank you for reporting the issue and helping us to do the addon better ;)

**Comment by ihorman** [comment] 2017-03-13 04:08
works fine now so closing the ticket, thanks ;)

**Closed by ihorman** 2017-03-13 04:08 UTC
