### ISSUE TITLE
The operation could not be performed

### ISSUE THREAD

**Issue by tblkoff** [jelastic-jps/lets-encrypt#23] opened 2017-08-19 15:46 UTC
`{"result":0},{"result":4109,"error":"The operation could not be performed","source":"JEL","responses":[{"result":4109,"error":"The operation could not be performed","source":"JEL","errOut":"--2017-08-19 15:38:57--  https://raw.githubusercontent.com/jelastic-jps/lets-encrypt/master/scripts/auto-update-ssl-cert.sh?_r=0.6997932726431145\nResolving raw.githubusercontent.com... 151.101.36.133\nConnecting to raw.githubusercontent.com|151.101.36.133|:443... connected.\nERROR: certificate common name \u201cwww.github.com\u201d doesn\u2019t match requested host name \u201craw.githubusercontent.com\u201d.\nTo connect to raw.githubusercontent.com insecurely, use \u2018--no-check-certificate\u2019.","exitStatus":5,"out":"","nodeid":70642}]},{}]},"result":0}`

**Comment by siruslan** [comment] 2017-08-20 12:53
@tblkoff, do you get the same error every time you install LE addon? Please provide more details about your environment name and service provider you use.

**Comment by tblkoff** [comment] 2017-08-21 13:49
Hi!
Provider app.jelastic.regruhosting.ru.
Got this error two times for two projects during installation, but certs installed successfully.
Can this affect the auto-update in the future?

**Comment by ihorman** [comment] 2017-11-02 16:16
@tblkoff, the problem is fixed in a code, could you please re-install addon, then installation and auto update should work fine, could you please try and let us know if the problem is resolved
thank you

**Comment by ihorman** [comment] 2018-02-14 14:06
the issue is fixed and merged to master

**Closed by ihorman** 2018-02-14 14:06 UTC
